<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>NflVerseRosterService_Std</RootNamespace>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)NflVerseRosterService-Std.dll&quot; &quot;d:\dropbox\services\&quot; /D /Y /I" />
  </Target>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NameFixerService-Std">
      <HintPath>..\..\..\..\Dropbox\Services\NameFixerService-Std.dll</HintPath>
    </Reference>
    <Reference Include="PlayerService-2.0">
      <HintPath>..\..\..\..\Dropbox\Services\PlayerService-2.0.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
